name: zerodezenove
description: A new Flutter project.
publish_to: 'none' 
version: 0.0.1
versionCode: 4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.3
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  google_fonts: ^2.0.0
  material_design_icons_flutter: 5.0.5955-rc.1
  flutter_feather_icons: ^2.0.0+1
  shimmer: ^2.0.0
  url_launcher: ^6.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/brand/
    - assets/lang/
    - assets/icons/
    - assets/images/profile/
    - assets/images/apps/grocery/
    - assets/illustration/food/
    - assets/illustration/shopping/
    - assets/illustration/hotel/
    - assets/illustration/music/
    - assets/images/month_background/
    
